### ISSUE TITLE
Parties / Gatherings / Multiple Wishlists

### ISSUE THREAD

**Issue by panreach** [imacrayon/snowbodyknows#23]
In the main description it says: 

> A user can build a wishlist and everybody else can check things off of it without the user being able to see.

Currently the functionality allows a user to see another's wish list and check a box.  The only other action item is the "leave this wishlist."

Wouldn't it be cool to see other user wishlists in the same party/gathering?

Using the `parties` name, a db structure could look like this?

`parties`
`parties_users`
`parties_wishlists`

**Comment by panreach** [comment]
I might want to use this same website/service for my work family, my wife's family, and my bother's family on three separate occasions.

**Comment by imacrayon** [comment]
Nice, I really like this idea! It would make sharing a lot easier.
