### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by sebcar** [imacrayon/snowbodyknows#26]
How can I help?

I'm the one who post [this](https://www.reddit.com/r/PHP/comments/17nrasm/contributing_to_php_open_source_project/) on Reddit.

**Comment by imacrayon** [comment]
Hi! Would you want to take a crack at #27 ? @panreach is also working on a new "parties" feature (#24) that they might need some help on, but I'll let them chime in.

**Comment by sebcar** [comment]
Sure, I'll try #27

**Comment by panreach** [comment]
This will be a fun one to work on:

`Add component to search google maps for location to autopopulate the lat/lng below based off of address`

https://github.com/panreach/snowbodyknows/blob/23-parties/resources/views/parties/_fields.blade.php#L18

**Comment by sebcar** [comment]
What's next?

**Comment by imacrayon** [comment]
I'm gonna close this out. We'll keep the issue tab current with any more help needed. Thanks!
