### ISSUE TITLE
Add the ability to delete a wishlist

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/snowbodyknows#27]
Thanks to #22 we can create new wishlists, but now users will need to be able to remove wishlists they no longer want. A route and basic controller method already exist for the delete action in `WishlistController::destroy` but that method should be improved a bit:

1. There should be some kind of confirmation before deleting a wishlist. We could copy the confirmation modal in `views/profiles/partials/delete-user-form.blade.php`. Maybe place it on the "Edit Wishlist" page? It should probably ask the user to type in the name of the wishlist before deleting.
2. The user should not be able to delete all of their wishlists. They should always have one "primary" list to add to.

**Comment by sebcar** [comment]
I'm working on this:

![image](https://github.com/imacrayon/snowbodyknows/assets/11927587/97c0058c-0131-4453-b176-afcdaecb419f)

I hope I can finish the phpunit tests in a few days

**Comment by imacrayon** [comment]
Looking good! Thanks for the update & let me know if you need anything.
