### ISSUE TITLE
Allow building a wishlist without an account

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/snowbodyknows#32]
People could demo creating an wishlist before registering. They would need to register in order to save their wishlist or share it.

**Comment by sebcar** [comment]
The data should be stored temporarily in session?

**Comment by imacrayon** [comment]
Yeah I think that would be the way to go.

**Comment by sebcar** [comment]
Ok, I'll take this issue.

**Comment by sebcar** [comment]
Is the link to create wishlist ok in "Build a whishlist" or it's better in the "Get Started" button?
![image](https://github.com/imacrayon/snowbodyknows/assets/11927587/e676b3f7-5a6a-47a0-a33d-ad1e05774e29)

**Comment by imacrayon** [comment]
@sebcar you can use the "Get Started" button.

**Comment by sebcar** [comment]
I'm trying to find a way to create a Guest user and use that structure to store in session and have minimal impact in the code (routes, policies, etc). Any suggestions?

**Comment by imacrayon** [comment]
It might be easier to duplicate some of the code rather than trying to make it work with a guest user. Maybe you could copy`WishlistController::show` and the whole `WishController`, rename them to something like `GuestWishlistController` and `GuestWishController`. Then you could modify them to store wishes in an array in the session instead of the database. When a user registers you can pull copy all the wishes from the session and add them to a new wishlist in the database.

**Comment by sebcar** [comment]
**Ok, let's do that.** 
I was reading about this aproach: [https://www.cardboardmachete.com/blog/anonymous-users](https://www.cardboardmachete.com/blog/anonymous-users) . Except for the part that store the user in DB and then clean it, seems pretty cool.

**Comment by imacrayon** [comment]
Cool, yeah, I think that would be a great solution if we wanted to allow guests to demo all of the app’s features.  Since we really only want them adding wishes I think it could cause a lot of extra work to limit what they can do and clean up all the edge cases.

**Comment by sebcar** [comment]
I'm trying to keep the model object structure (`App\Model\Wishlist` and `App\Model\Wish`) in the controllers so we don't have to change too much in the views (but I've duplicated the views: `guest.wishlist.show`, `guest.wish.create`, etc)

![image](https://github.com/imacrayon/snowbodyknows/assets/11927587/692c891c-f8fa-40a9-aee0-5be86b504158)

**Comment by imacrayon** [comment]
Looks good! Yeah I wouldn’t worry too much about duplicate code right now. We can always refactor and DRY it up later.

**Comment by sebcar** [comment]
The wish CRUD as a guest is done, but I need some advice about the testing, any suggestions? This is what I have.

```php
<?php

const DEFAULT_WISHLIST = [
    'name' => 'My wishlist',
    'id' => 0,
    'wishes' => []
];

test('guest see the default wishlist', function() {
    $response = $this->get(route('guest.wishlists.show'));

    $response->assertOk();
    $this->assertGuest();
});

test('guest add a wish', function() {
    $response = $this->withSession(['wishlist' => DEFAULT_WISHLIST])
                        ->post(route('guest.wishes.create'), [
        'name' => 'New Wish',
        'url' => 'https://imacrayon.com',
        'description' => 'Test description.',
    ]);
     
    $response->assertRedirectToRoute('guest.wishlists.show');

    $response->assertSessionHas('wishlist', function(array $wishlist){
        return 
            $wishlist['wishes'][0]['name'] === 'New Wish' &&
            $wishlist['wishes'][0]['url'] === 'https://imacrayon.com' &&
            $wishlist['wishes'][0]['description'] === 'Test description.';
    }) ;
    
});
```

**Comment by imacrayon** [comment]
@sebcar those tests look alright to me. Was there something specific you weren't sure about?

**Comment by sebcar** [comment]
I wasn't sure about the way that I did the session testing.
