### ISSUE TITLE
Add UI for wishlist name change

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/snowbodyknows#4]
The controller logic, routes, and tests already exist to allow a user to rename their wishlist. We need to build out a UI for the `wishlist.edit` and `wishlist.update` routes.

**Comment by AbdullahTheDev** [comment]
You mean, to redesign Edit page? If yes then please assign this task to me I'll redesign it better.

**Comment by imacrayon** [comment]
Yes, you can update the view markup to match the [edit wish page](https://github.com/imacrayon/snowbodyknows/blob/production/resources/views/wishes/edit.blade.php) and then you’ll need to add an “Edit” link on the Show Wishlist page. Probably best to add the link next to the Wishlist’s name.

**Comment by AbdullahTheDev** [comment]
Ok

**Comment by imacrayon** [comment]
@AbdullahTheDev any more info you need from me? Is it ok to keep you assigned to this?
