### ISSUE TITLE
Add a homepage

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/snowbodyknows#5]
Looking for copy, design, or whatever for a good looking, simple, homepage. [The template code is here](https://github.com/imacrayon/snowbodyknows/blob/production/resources/views/welcome.blade.php), I'll accept WIP PRs since anything would be better than what's currently there.

**Comment by ShikhaaT44** [comment]
I'm interested on working on this issue!

**Comment by imacrayon** [comment]
@ShikhaaT44 just checking in - are you still interested in working on this? Anything you need from me?

**Comment by ShikhaaT44** [comment]
@imacrayon , i would like to get unassigned from this issue since i tried multiple times but facing errors while setting up the project environment due to some technical issues in my machine.  Apologies for failing to complete the issue.

**Comment by imacrayon** [comment]
@ShikhaaT44 no problem! If you're still interested in getting the app working you can fine me under the same username in the official Laravel Discord. I could try to help get you setup - no pressure though 😄
