### ISSUE TITLE
Fix page titles

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/snowbodyknows#6]
Many pages do not have a unique page title set. [Check this template markup to see how to set the page title](https://github.com/imacrayon/snowbodyknows/blob/feb9993a3c64a6778bada8ec2d162a82c3c4dc74/resources/views/wishlists/viewers/create.blade.php#L1).

**Comment by ihtishamKhan** [comment]
Hey, I am starting work on this. Please assign this to me
