### ISSUE TITLE
Indicate the numer of wishes a wishlist has

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/snowbodyknows#9]
Display the number of wishes a wishlist has under each wishlist's name on [/wishlists](https://snowbodyknows.com/app/wishlists) page.

To get started on this add a `withCount('wishes')` to each query  in `WishlistController::index`.

**Comment by AbdullahTheDev** [comment]
Hi @imacrayon, can you please assign this task to me? I want to work on it, also please give it hacktoberfest label.

**Comment by AbdullahTheDev** [comment]
Is this what you want?
This is how wishes count shown?
Or something different you want, please tell me so I can change it to that.

![ok](https://github.com/imacrayon/snowbodyknows/assets/92722046/c8dda076-3d93-4810-ad91-037cc173ec61)

**Comment by imacrayon** [comment]
> Is this what you want?

Looks good, add “wishes” after the count so that it’s more clear, and it will be perfect.

**Comment by AbdullahTheDev** [comment]
ok sir
